language: cpp

os: osx

compiler:
    - clang

script: 
    - mkdir -p build/macos
    - cd build/macos
    - cmake ../.. -DCMAKE_BUILD_TYPE=Release
    - cmake --build .

notifications:
    email: false
