language: cpp

os: osx

compiler:
  - clang

install:
# Install conan and detect arch/compiler/etc.
  - pip install conan
  - conan user

script:
  - mkdir -p build/macos
  - ./run-conan.sh
  - cd build/macos
  - cmake ../.. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .

notifications:
  email: false
